language: php

php:
    - '7.0'
    - '7.1'

addons:
    mariadb: '10.1'

cache:
    yarn: true
    directories:
        - node_modules
        - vendor

before_install:
    - nvm install node

before_script:
    - phpenv config-rm xdebug.ini
    - mysql -e 'CREATE DATABASE travis_testing'
    - cp .env.travis .env
    - php artisan key:generate
    - php artisan migrate --seed

install:
    - composer install --no-interaction --no-dev
    - yarn

script:
    - npm run prod
    - vendor/bin/phpunit

notifications:
    email: false