language: php
sudo: false

php:
    - '7.1'

addons:
    mariadb: '10.1'

cache:
    yarn: true
    directories:
        - node_modules
        - vendor

before_install:
    - nvm install node
    - composer require satooshi/php-coveralls:dev-master

before_script:
    - phpenv config-rm xdebug.ini
    - mysql -e 'CREATE DATABASE travis_testing'
    - cp .env.travis .env
    - php artisan key:generate
    - php artisan migrate --seed

install:
    - composer install --no-interaction
    - yarn

script:
    - yarn run prod
    - ./vendor/bin/phpunit --coverage-clover coverage.xml

after_script:
  - ./vendor/bin/coveralls -v

notifications:
    email: false
